apiVersion: v1
kind: Service
metadata:
  name: serviceapp2
spec:
  ports:
    - nodePort: 31290
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: serviceapp2
  type: NodePort
